# _config.yml

title: Schauer-Mayhew designs
description: >
  Interior Design by Addam Mayhew. Photography by Bryan Schauer. SMd. specializes in creative interiors and visual storytelling.
url: "https://www.schauermayhew.com"
baseurl: "" # No subdirectory
remote_theme: mmistakes/minimal-mistakes

navbar-links:
  "Interior Design": "interior"
  "Photography": "photo"
  "About": "about"
  "Contact": "contact"

social-network-links:
  email: "addam@schauermayhew.com"
  linkedin: "https://www.linkedin.com/in/addam-mayhew-8669b123/"
  # github: "https://github.com/igotsidetrackded"
  # flickr: "https://flickr.com/schauebc"
  # bluesky: "https://bsky.app/profile/igotsidetrackded.bsky.social"

author: Bryan Schauer
#author:
  #name: "Addam Mayhew"
  #email: "addam@schauermayhew.com"
  #bio: "Interior Designer, Freelancer, Creative"
  #avatar: "/assets/interior/addam-avatar.jpg"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

gtag: "G-YKGHSETFP2"
gtm: "GTM-K3WRN57"

# Collections for portfolio
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Navigation (Minimal Mistakes uses navigation.yml, but topnav can be inline too)
include: ["_pages"]
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

markdown: kramdown
highlighter: rouge
permalink: pretty

