# _config.yml

title: Schauer-Mayhew designs
description: >-
  Interior Design by Addam Mayhew. Photography by Bryan Schauer. SMd. specializes in creative interiors and visual storytelling.
url: "https://www.schauermayhew.com"
baseurl: "" # No subdirectory
theme: beautiful-jekyll-theme

# Branding colors
primary_color: "#b22222" # Addam's red
secondary_color: "#888589" # Bryan's accent (grey)

# Navigation
navbar-links:
  "Interior Design": "/interior"
  "Photography": "/photo"
  "About": "/about"
  "Contact": "/contact"

# Social links
social-network-links:
  email: "addam@schauermayhew.com"
  linkedin: "https://www.linkedin.com/in/addam-mayhew-8669b123/"
#  github: "https://github.com/igotsidetrackded"
#  flickr: "https://flickr.com/schauebc"
#  bluesky: "https://bsky.app/profile/igotsidetrackded.bsky.social"

# Author info
author:
  name: "Addam Mayhew"
  email: "addam@schauermayhew.com"
  bio: "Interior Designer, Freelancer, Creative"
  avatar: "/assets/interior/addam-avatar.jpg"

# Plugins (if needed)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

gtag: "G-YKGHSETFP2"
gtm: "GTM-K3WRN57"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Other settings
markdown: kramdown
highlighter: rouge
permalink: pretty

