title: Schauer-Mayhew designs
description: >
  Interior Design by Addam Mayhew. Photography by Bryan Schauer.
url: "https://www.schauermayhew.com"
baseurl: "" # root

# Minimal Mistakes remote theme
remote_theme: mmistakes/minimal-mistakes

# Plugins supported by GitHub Pages
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Defaults for pages and projects
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      classes: wide

# Navigation uses _data/navigation.yml
include: ["_pages"]

permalink: pretty
markdown: kramdown
highlighter: rouge

# Analytics (optional; keep if used)
gtag: "G-YKGHSETFP2"
gtm: "GTM-K3WRN57"

# Social (Minimal Mistakes supports 'author' differently; use site-wide links)
social:
  - title: "LinkedIn"
    url: "https://www.linkedin.com/in/addam-mayhew-8669b123/"
  - title: "Email"
    url: "mailto:addam@schauermayhew.com"

# Minimal Mistakes settings
minimal_mistakes_skin: "default" # we’ll override color via SCSS

sass:
  sass_dir: assets/css

